### ISSUE TITLE
DeepLabel Tool not able to output labels

### ISSUE THREAD

**Issue by shashank2408** [jveitchmichaelis/deeplabel#1]
I have  series of images which I labeled using the deep label tool. I exported the labels and stored it in a directory. I observe two issues:
1. If the directory to store the images is not present, the tool creates a new directory within the desired directory. 
Eg: Folder Name: YOLO_Train 
Output - YOLO_Train -> YOLO_Train  -> (train ,val ). Both the folders are empty 
2. If the directory is present, the tool is able to store all the images in the directory with the label files but the label files are empty. There are no bounding box coordinates 

Please let me know if there is a specific procedure to follow to export labels. I feel that tool is able to record the bounding boxes but not output the coordinates into the file.

**Comment by jveitchmichaelis** [comment]
@shashank2408 Thanks for the bug report. I've made a few fixes, if you're building from source then please pull and recompile. Otherwise, I'll put up a new release shortly!

1. The double folder issue should be fixed. I can't reproduce it now.

2. Do you have a names file to go with your data? I've added some more debug messages, so check the console when you try to export your project.

DeepLabel will try to match class names (converted to lower case) you've used to label your images with an existing names file so that the output labels have the correct class ID regardless of what order you created the classes in your project. This is mostly useful if you want to export multiple label projects together into one folder. If your class labels aren't found in the names file, then those labels won't be exported. You should at least get a debug message now. A names file is just a plain text file with each class on a new line.

The procedure is as you followed - label your images, set an output folder, set a names file and then export.

**Comment by shashank2408** [comment]
Got it to work! Thanks
