### ISSUE TITLE
support on yolov4 and yolov5

### ISSUE THREAD

**Issue by brianng0305** [jveitchmichaelis/deeplabel#17]
Hi. Deeplabel said it did not support yolov4.weight to detect.

**Comment by jveitchmichaelis** [comment]
Thanks, I agree this would be useful. 

However I'm not sure where the problem lies, as this is fairly recent and I haven't tested with Yolov4. The backend uses OpenCV for detection so if it doesn't work you might want check if it's supported there first. I do have a plan to move to the cuda version of OpenCV DNN for speed.

See https://github.com/opencv/opencv/pull/17185 - check that you have the latest version of OpenCV. If you're building using homebrew on Mac you might need to build deeplabel from scratch, as well as building opencv from master.

The newer versions of Yolo use different activation functions etc to v3, for example.

Alternatively we could consider bundling darknet with deeplabel for better training integration, but that's not a huge priority right now. Probably easier to use the darknet library than wait for opencv, and we would get cuda support for free. It would greatly increase the dependencies though and some people don't have GPUs so we might need to worry about different darknet versions. 

Also yolov5, as far as I'm aware, is only in Pytorch. 

I'm closing for now as this doesn't seem to be released by opencv yet (as a specific version) and is therefore not an issue with deeplabel.
